version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.0
      - image: postgres:13
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admincontroller
          POSTGRES_DB: admincontroller
    parallelism: 2
    environment:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admincontroller
      POSTGRES_DB: admincontroller_test
    steps:
      - checkout

      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://localhost:5432 -timeout 60s

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run parallel tests
          command: |
            TEST_FILES=$(circleci tests glob "tests/**/*.test.js" | circleci tests split)
            npx jest $TEST_FILES

      - run:
          name: Send GitHub status notification
          when: always
          command: |
            COMMIT_SHA=$(git rev-parse HEAD)
            BUILD_STATE="success"
            DESCRIPTION=$(if [ "$BUILD_STATE" = "success" ]; then echo "Pipeline completado exitosamente."; else echo "Pipeline fallido."; fi)
      
            curl -X POST -H "Authorization: token ${CIRCLE_TOKEN}" \
                 -H "Accept: application/vnd.github+json" \
                 -H "X-GitHub-Api-Version: 2022-11-28" \
                 --data "{\"state\":\"${BUILD_STATE}\",\"description\":\"${DESCRIPTION}\",\"context\":\"CI/CD - CircleCI\"}" \
                 https://api.github.com/repos/JossueJativa/websocket/statuses/${COMMIT_SHA}


workflows:
  version: 2
  github-flow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - circleci-project-setup
