version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.0
      - image: cimg/postgres:13.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admincontroller
          POSTGRES_DB: admincontroller
    environment:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admincontroller
      POSTGRES_DB: admincontroller_test
    steps:
      - checkout
      - run:
          name: Wait for PostgreSQL to be ready
          command: |
            dockerize -wait tcp://localhost:5432 -timeout 60s
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  github-flow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main
                - /pull\/.*/ # Pull requests
